# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        thumb:
            quality: 100
            filters:
                thumbnail: { size: [ 600, 600 ], mode: inset }